# adapted from https://github.com/patrick-kidger/equinox/blob/main/mkdocs.yml
theme:
    name: material
    features:
        - navigation.sections
        - toc.integrate
        - header.autohide
        - content.code.copy
    palette:
        - scheme: slate
          primary: black
          accent: amber
    icon:
        repo: fontawesome/brands/github

site_name: thrml-boost
site_description: The documentation for the thrml-boost library.
site_author: thrml-boost contributors
site_url: ""

repo_url: https://github.com/dek3rr/thrml-boost
repo_name: thrml-boost
edit_uri: ""

strict: false

extra_javascript: 
    # The below two make MathJax work, see https://squidfunk.github.io/mkdocs-material/reference/mathjax/
    - _static/mathjax.js
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
    - _static/video_handler.js

extra_css:
    - _static/custom_css.css

markdown_extensions:
    - pymdownx.arithmatex:
        generic: true
    - pymdownx.superfences
    - pymdownx.details
    - pymdownx.snippets:
        base_path: docs
    - admonition
    - toc:
        permalink: "Â¤"
        toc_depth: 4

plugins:
    - search:
        # See https://github.com/squidfunk/mkdocs-material/discussions/8116#discussioncomment-12632752
        # and https://github.com/patrick-kidger/equinox/issues/984
        separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'
    - include_exclude_files:
        include:
            - ".htaccess"
        exclude:
            - "examples/.ipynb_checkpoints/"
            - "examples/MNIST"
            - "examples/bert_checkpoint.eqx"
    - ipynb
    - hippogriffe:
        extra_public_objects:
            - equinox.if_array
            - jax.ShapeDtypeStruct
            - jax.extend.core.ClosedJaxpr
            - jax.Device
            - jax.sharding.Sharding
            - numpy.dtype
            - jax.numpy.float32
    - mkdocstrings:
        handlers:
            python:
                options:
                    force_inspection: true
                    heading_level: 4
                    inherited_members: true
                    members_order: source
                    show_bases: false
                    show_if_no_docstring: true
                    show_overloads: false
                    show_root_heading: true
                    show_signature_annotations: true
                    show_source: false
                    show_symbol_type_heading: true
                    show_symbol_type_toc: true

nav:
    - 'index.md'
    - 'examples/00_probabilistic_computing.ipynb'
    - Examples:
        - 'examples/01_all_of_thrml.ipynb'
        - 'examples/02_spin_models.ipynb'
        - 'examples/03_parallel_tempering.ipynb'
    - API Reference:
        - 'api/pgm.md'
        - 'api/block_management.md'
        - 'api/interaction.md'
        - 'api/factor.md'
        - 'api/conditional_samplers.md'
        - 'api/block_sampling.md'
        - 'api/observers.md'
        - 'api/tempering.md'
        - Models:
            - 'api/models/ebm.md'
            - 'api/models/discrete_ebm.md'
            - 'api/models/ising.md'
    - Further details:
      - 'architecture.md'
